/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

/**
 * `circlekey/testing`: in-memory adapters for
 * tests, examples, and host-app integration suites. `MockTransport`
 * doubles as the executable reference of the backend's spec §10
 * obligations — a host backend is conformant when the client behaves
 * identically against it.
 */

import { WebCryptoProvider } from "./adapters/crypto/web";
import { InProcessLockProvider } from "./adapters/locks";
import { MemoryStore } from "./adapters/storage/memory";
import { GroupVault } from "./api/group-vault";
import { authorizeRelayRequest } from "./core/relay-auth";
import type { BackupManagerOptions } from "./managers/backup-manager";
import type { EncryptedRecord } from "./core/types";
import type { CryptoProvider } from "./ports/crypto-provider";
import type { Transport } from "./ports/transport";

export { MemoryStore } from "./adapters/storage/memory";
export { MockTransport } from "./adapters/transport/mock";
export type { MockTransportOptions } from "./adapters/transport/mock";
export { InProcessLockProvider } from "./adapters/locks";
export { InProcessHintChannel, NoopHintChannel } from "./adapters/hints";

export interface HostIntegrationOptions {
  /** Build the Transport under test — your backend adapter. */
  makeTransport: () => Transport | Promise<Transport>;
  /** Defaults to `WebCryptoProvider` (requires a secure context / Node ≥ 20). */
  crypto?: CryptoProvider;
  /**
   * Backup KDF overrides (spec §6.2). Reducing the Argon2id cost keeps
   * the scenario fast; the default is the conforming baseline.
   */
  backup?: BackupManagerOptions;
}

export interface HostIntegrationReport {
  groupId: string;
  /** Every assertion that passed, in order. */
  checks: string[];
}

/**
 * The host-integration acceptance scenario. Run it against your
 * own `Transport` adapter: if it completes, your backend honors the
 * client-observable spec §10 obligations the same way `MockTransport`
 * (the executable reference) does. Throws with the failing check's
 * label otherwise.
 *
 * The scenario exercises: the mandatory-backup gate, group creation,
 * records across epochs, member onboarding with full-history
 * decryption, governance by a promoted member, convergence via
 * polling, removal semantics, and lost-device restore. It creates
 * uniquely named users/groups so it can run repeatedly against a
 * persistent backend.
 */
export async function runHostIntegrationScenario(
  options: HostIntegrationOptions,
): Promise<HostIntegrationReport> {
  const transport = await options.makeTransport();
  const checks: string[] = [];
  const pass = (label: string): void => {
    checks.push(label);
  };
  const ensure = (condition: boolean, label: string): void => {
    if (!condition) throw new Error(`host integration scenario failed at: ${label}`);
    pass(label);
  };
  const expectRejection = async (
    operation: Promise<unknown>,
    label: string,
  ): Promise<void> => {
    try {
      await operation;
    } catch {
      pass(label);
      return;
    }
    throw new Error(
      `host integration scenario failed at: ${label} (operation unexpectedly succeeded)`,
    );
  };

  const suffix = `${Date.now().toString(36)}-${Math.floor(Math.random() * 36 ** 4).toString(36)}`;
  // Only the user ids are caller-chosen and suffixed, so the scenario
  // can run repeatedly against a persistent backend. The group id is
  // generated by `createGroup` (spec §6.5) and learned below.
  const aliceId = `ck-int-alice-${suffix}`;
  const bobId = `ck-int-bob-${suffix}`;

  const aliceStorage = new MemoryStore();
  const openVault = (userId: string, storage: MemoryStore): Promise<GroupVault> =>
    GroupVault.open({
      transport,
      userId,
      storage,
      locks: new InProcessLockProvider(),
      requestPersistentStorage: false,
      ...(options.crypto === undefined ? {} : { crypto: options.crypto }),
      ...(options.backup === undefined ? {} : { backup: options.backup }),
    });

  // --- Alice onboards; the backup gate must hold. ---
  const alice = await openVault(aliceId, aliceStorage);
  await expectRejection(
    alice.createGroup({ min_managers: 1 }),
    "backup gate blocks group ops pre-enrollment (spec §9.6)",
  );
  const credential = await alice.enrollBackup();
  ensure(credential.length >= 22, "enrollment returns a >=128-bit recovery credential");
  // spec §9.6: issuing the credential is not enough — the gate stays
  // shut until the user confirms they stored it.
  await expectRejection(
    alice.createGroup({ min_managers: 1 }),
    "backup gate stays shut until the credential is confirmed (spec §9.6)",
  );
  await alice.confirmBackupStored(credential);
  const groupId = (await alice.createGroup({ min_managers: 1 })).group_id;
  ensure(
    groupId.length === 22 && !groupId.includes("circlekey"),
    "createGroup generated an opaque group id rather than taking one (spec §6.5)",
  );
  await alice.putJsonRecord(groupId, "doc-pre", { phase: "before-join" });
  pass("record stored under epoch 0");

  // --- Bob joins and inherits the full history. ---
  const bob = await openVault(bobId, new MemoryStore());
  await bob.confirmBackupStored(await bob.enrollBackup());
  await alice.addMember(groupId, { userId: bobId, devicePubkey: bob.devicePublicKey() });
  pass("addMember accepted");
  const bobState = await bob.syncGroup(groupId);
  ensure(bobState.epoch === 1, "member converged via polling");
  const preJoin = await bob.getJsonRecord(groupId, "doc-pre");
  ensure(
    JSON.stringify(preJoin) === JSON.stringify({ phase: "before-join" }),
    "pre-join record decrypted via the spec §9.7 history chain",
  );

  // --- Governance by a promoted member; both sides converge. ---
  await alice.promoteMember(groupId, bobId);
  await bob.syncGroup(groupId);
  await bob.setPolicy(groupId, { min_managers: 1 });
  pass("promoted member performed a governance op");
  const converged = await alice.syncGroup(groupId);
  ensure(converged.epoch === 3, "manager converged after peer's op");

  // --- Removal cuts future access (spec §9.3). ---
  await alice.removeMember(groupId, bobId);
  pass("removeMember accepted");
  await alice.putJsonRecord(groupId, "doc-post", { phase: "after-removal" });
  // a removed member cannot *open* the removal
  // transition — its body is sealed to a secret they no longer receive
  // — so they do not advance to it. They observe loss of access rather
  // than a verified removal (spec §6.5, §9.3), which is stricter: they
  // also learn nothing about the post-removal membership.
  const bobAfter = await bob.syncGroup(groupId);
  ensure(
    bobAfter.epoch === converged.epoch &&
      bobAfter.members.some((member) => member.user_id === bobId),
    "removed member stops at its last accessible epoch",
  );
  await expectRejection(
    bob.getJsonRecord(groupId, "doc-post"),
    "removed member cannot read post-removal data",
  );

  // --- Lost device: restore from the credential (spec §9.6). ---
  const restored = await GroupVault.restore({
    transport,
    userId: aliceId,
    storage: new MemoryStore(),
    locks: new InProcessLockProvider(),
    requestPersistentStorage: false,
    credential,
    ...(options.crypto === undefined ? {} : { crypto: options.crypto }),
    ...(options.backup === undefined ? {} : { backup: options.backup }),
  });
  await restored.syncGroup(groupId);
  const post = await restored.getJsonRecord(groupId, "doc-post");
  ensure(
    JSON.stringify(post) === JSON.stringify({ phase: "after-removal" }),
    "lost device restored from backup and recovered full access",
  );

  // --- Relay authorization (spec §10.1, §10.5). ---
  //
  // Everything above runs through `GroupVault`, so a relay that ignores
  // request signatures entirely would still reach this line. These
  // checks address the relay directly, because the read/write split is
  // the obligation most likely to be implemented as one rule — and
  // getting it wrong in the tempting direction (require the current key
  // everywhere) deadlocks every client that falls behind.
  const crypto = options.crypto ?? new WebCryptoProvider();
  const currentEpoch = alice.getGroupState(groupId)?.epoch ?? 0;
  const staleSecret = await aliceStorage.getGroupSecret(groupId, 0);
  const currentSecret = await aliceStorage.getGroupSecret(groupId, currentEpoch);
  ensure(
    currentEpoch > 0 && staleSecret !== undefined && currentSecret !== undefined,
    "scenario reached a multi-epoch group with its secrets available",
  );
  if (staleSecret !== undefined && currentSecret !== undefined && currentEpoch > 0) {
    // A lagging reader MUST be able to catch up with an old key.
    await transport.getTransitions(
      groupId,
      undefined,
      await authorizeRelayRequest(crypto, groupId, "getTransitions", 0, staleSecret),
    );
    pass("read accepted with a stale epoch key (no catch-up deadlock, spec §10.1)");

    // Writes are the other half of the split. Tagged at the current
    // epoch so the freshness gate passes and only the signature can be
    // what refuses it — otherwise this would pass for the wrong reason.
    const staleWrite: EncryptedRecord = {
      record_id: `ck-int-authprobe-${suffix}`,
      epoch: currentEpoch,
      ciphertext: "probe",
      nonce: "probe",
      suite: "gv1",
    };
    await expectRejection(
      transport.putRecord(
        groupId,
        staleWrite,
        await authorizeRelayRequest(crypto, groupId, "putRecord", 0, staleSecret),
      ),
      "write refused when signed with a stale epoch key (spec §10.1)",
    );
    await expectRejection(
      transport.putRecord(
        groupId,
        staleWrite,
        await authorizeRelayRequest(
          crypto,
          groupId,
          "putRecord",
          currentEpoch,
          crypto.randomBytes(32),
        ),
      ),
      "write refused when signed with a key the group never published",
    );
    // Reads may bootstrap through the relay's own account layer; writes
    // never do. A caller that cannot sign is not a member (spec §10.5).
    await expectRejection(
      transport.putRecord(groupId, staleWrite),
      "unsigned write refused (writes never bootstrap, spec §10.5)",
    );
  }

  return { groupId, checks };
}
